DROP TABLE DemoEntity IF EXISTS;

CREATE TABLE DemoEntity (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
  updtimestamp timestamp default SYSDATE,
  description VARCHAR(100) NOT NULL,
  PRIMARY KEY(id)
);

CREATE TABLE SecondEntity (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
  updtimestamp timestamp default SYSDATE,
  extraProperty VARCHAR(100) NOT NULL,
  demoEntity BIGINT NOT NULL,
  PRIMARY KEY(id),
  FOREIGN KEY (demoEntity) REFERENCES DemoEntity(id)
);

CREATE TABLE TemplateFile (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
  updtimestamp timestamp default SYSDATE,
  templateName VARCHAR(100) NOT NULL,
  description VARCHAR(1000) NOT NULL,
  excelTemplate VARCHAR(1000) NOT NULL,
  photo VARCHAR(1000) NOT NULL,
  sqlQuery VARCHAR(1000) NOT NULL,
  PRIMARY KEY(id)
);

CREATE TABLE ExcelFile (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
  updtimestamp timestamp default SYSDATE,
  fileName VARCHAR(100) NOT NULL,
  file VARCHAR(1000) NOT NULL,
  startDate timestamp default SYSDATE,
  endDate timestamp default SYSDATE,
  templateFile BIGINT NOT NULL,
  PRIMARY KEY(id),
  FOREIGN KEY (templateFile) REFERENCES TemplateFile(id)
);

CREATE TABLE DownloadInfo (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
  updtimestamp timestamp default SYSDATE,
  excelFile BIGINT NOT NULL,
  username VARCHAR(100) NOT NULL,
  PRIMARY KEY(id),
  FOREIGN KEY (excelFile) REFERENCES ExcelFile(id)
);